# Generated by Django 4.1.2 on 2024-02-29 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vectorWoodcrafts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='tel',
            new_name='phone_no',
        ),
        migrations.RemoveField(
            model_name='user',
            name='type',
        ),
    ]
