# Generated by Django 4.1.2 on 2024-02-29 08:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vectorWoodcrafts', '0002_rename_tel_user_phone_no_remove_user_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Customer',
        ),
    ]
